//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mitutoyo.MiCAT.ReportModule.GUI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Mitutoyo.MiCAT.ReportModule.GUI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALL.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to continue?.
        /// </summary>
        public static string AreYouSureToContinue {
            get {
                return ResourceManager.GetString("AreYouSureToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blank.
        /// </summary>
        public static string Blank {
            get {
                return ResourceManager.GetString("Blank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Blank).
        /// </summary>
        public static string BlankStatus {
            get {
                return ResourceManager.GetString("BlankStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAD View.
        /// </summary>
        public static string CADViewString {
            get {
                return ResourceManager.GetString("CADViewString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string CancelButtonLabel {
            get {
                return ResourceManager.GetString("CancelButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D.
        /// </summary>
        public static string CharacteristicDetail_2D {
            get {
                return ResourceManager.GetString("CharacteristicDetail_2D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3D.
        /// </summary>
        public static string CharacteristicDetail_3D {
            get {
                return ResourceManager.GetString("CharacteristicDetail_3D", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg.
        /// </summary>
        public static string CharacteristicDetail_Avg {
            get {
                return ResourceManager.GetString("CharacteristicDetail_Avg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DA.
        /// </summary>
        public static string CharacteristicDetail_DA {
            get {
                return ResourceManager.GetString("CharacteristicDetail_DA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter 2.
        /// </summary>
        public static string CharacteristicDetail_Diameter_2 {
            get {
                return ResourceManager.GetString("CharacteristicDetail_Diameter 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DR.
        /// </summary>
        public static string CharacteristicDetail_DR {
            get {
                return ResourceManager.GetString("CharacteristicDetail_DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DX.
        /// </summary>
        public static string CharacteristicDetail_DX {
            get {
                return ResourceManager.GetString("CharacteristicDetail_DX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DY.
        /// </summary>
        public static string CharacteristicDetail_DY {
            get {
                return ResourceManager.GetString("CharacteristicDetail_DY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DZ.
        /// </summary>
        public static string CharacteristicDetail_DZ {
            get {
                return ResourceManager.GetString("CharacteristicDetail_DZ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LC.
        /// </summary>
        public static string CharacteristicDetail_LC {
            get {
                return ResourceManager.GetString("CharacteristicDetail_LC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LL.
        /// </summary>
        public static string CharacteristicDetail_LL {
            get {
                return ResourceManager.GetString("CharacteristicDetail_LL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LMC.
        /// </summary>
        public static string CharacteristicDetail_LMC {
            get {
                return ResourceManager.GetString("CharacteristicDetail_LMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LS.
        /// </summary>
        public static string CharacteristicDetail_LS {
            get {
                return ResourceManager.GetString("CharacteristicDetail_LS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string CharacteristicDetail_Max {
            get {
                return ResourceManager.GetString("CharacteristicDetail_Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string CharacteristicDetail_Min {
            get {
                return ResourceManager.GetString("CharacteristicDetail_Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMC.
        /// </summary>
        public static string CharacteristicDetail_MMC {
            get {
                return ResourceManager.GetString("CharacteristicDetail_MMC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius 2.
        /// </summary>
        public static string CharacteristicDetail_Radius_2 {
            get {
                return ResourceManager.GetString("CharacteristicDetail_Radius 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC.
        /// </summary>
        public static string CharacteristicDetail_SC {
            get {
                return ResourceManager.GetString("CharacteristicDetail_SC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SL.
        /// </summary>
        public static string CharacteristicDetail_SL {
            get {
                return ResourceManager.GetString("CharacteristicDetail_SL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS.
        /// </summary>
        public static string CharacteristicDetail_SS {
            get {
                return ResourceManager.GetString("CharacteristicDetail_SS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Axis.
        /// </summary>
        public static string CharacteristicDetail_X_Axis {
            get {
                return ResourceManager.GetString("CharacteristicDetail_X-Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-Axis 2.
        /// </summary>
        public static string CharacteristicDetail_X_Axis_2 {
            get {
                return ResourceManager.GetString("CharacteristicDetail_X-Axis 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY Plane.
        /// </summary>
        public static string CharacteristicDetail_XY_Plane {
            get {
                return ResourceManager.GetString("CharacteristicDetail_XY Plane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY Ref. Plane.
        /// </summary>
        public static string CharacteristicDetail_XY_Ref__Plane {
            get {
                return ResourceManager.GetString("CharacteristicDetail_XY Ref. Plane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XY Ref. Plane 2.
        /// </summary>
        public static string CharacteristicDetail_XY_Ref__Plane_2 {
            get {
                return ResourceManager.GetString("CharacteristicDetail_XY Ref. Plane 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-Axis.
        /// </summary>
        public static string CharacteristicDetail_Y_Axis {
            get {
                return ResourceManager.GetString("CharacteristicDetail_Y-Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y-Axis 2.
        /// </summary>
        public static string CharacteristicDetail_Y_Axis_2 {
            get {
                return ResourceManager.GetString("CharacteristicDetail_Y-Axis 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YZ Ref. Plane.
        /// </summary>
        public static string CharacteristicDetail_YZ_Ref__Plane {
            get {
                return ResourceManager.GetString("CharacteristicDetail_YZ Ref. Plane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YZ Ref. Plane 2.
        /// </summary>
        public static string CharacteristicDetail_YZ_Ref__Plane_2 {
            get {
                return ResourceManager.GetString("CharacteristicDetail_YZ Ref. Plane 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-Axis.
        /// </summary>
        public static string CharacteristicDetail_Z_Axis {
            get {
                return ResourceManager.GetString("CharacteristicDetail_Z-Axis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-Axis 2.
        /// </summary>
        public static string CharacteristicDetail_Z_Axis_2 {
            get {
                return ResourceManager.GetString("CharacteristicDetail_Z-Axis 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZX Ref. Plane.
        /// </summary>
        public static string CharacteristicDetail_ZX_Ref__Plane {
            get {
                return ResourceManager.GetString("CharacteristicDetail_ZX Ref. Plane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZX Ref. Plane 2.
        /// </summary>
        public static string CharacteristicDetail_ZX_Ref__Plane_2 {
            get {
                return ResourceManager.GetString("CharacteristicDetail_ZX Ref. Plane 2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristic Name.
        /// </summary>
        public static string CharacteristicName {
            get {
                return ResourceManager.GetString("CharacteristicName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristic Table Section ({0} of {1}).
        /// </summary>
        public static string CharacteristicTable_PlaceHolder_FirstLine {
            get {
                return ResourceManager.GetString("CharacteristicTable_PlaceHolder_FirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch to REPORT mode to view data..
        /// </summary>
        public static string CharacteristicTable_PlaceHolder_SecondLine {
            get {
                return ResourceManager.GetString("CharacteristicTable_PlaceHolder_SecondLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristic Table.
        /// </summary>
        public static string CharacteristicTableString {
            get {
                return ResourceManager.GetString("CharacteristicTableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristic Type.
        /// </summary>
        public static string CharacteristicType {
            get {
                return ResourceManager.GetString("CharacteristicType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle.
        /// </summary>
        public static string CharacteristicType_Angle {
            get {
                return ResourceManager.GetString("CharacteristicType_Angle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angle coordinate.
        /// </summary>
        public static string CharacteristicType_AngleCoordinate {
            get {
                return ResourceManager.GetString("CharacteristicType_AngleCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angularity.
        /// </summary>
        public static string CharacteristicType_Angularity {
            get {
                return ResourceManager.GetString("CharacteristicType_Angularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circularity.
        /// </summary>
        public static string CharacteristicType_Circularity {
            get {
                return ResourceManager.GetString("CharacteristicType_Circularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular runout.
        /// </summary>
        public static string CharacteristicType_CircularRunout {
            get {
                return ResourceManager.GetString("CharacteristicType_CircularRunout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coaxiality.
        /// </summary>
        public static string CharacteristicType_Coaxiality {
            get {
                return ResourceManager.GetString("CharacteristicType_Coaxiality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentricity.
        /// </summary>
        public static string CharacteristicType_Concentricity {
            get {
                return ResourceManager.GetString("CharacteristicType_Concentricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conicity.
        /// </summary>
        public static string CharacteristicType_Conicity {
            get {
                return ResourceManager.GetString("CharacteristicType_Conicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cylindricity.
        /// </summary>
        public static string CharacteristicType_Cylindricity {
            get {
                return ResourceManager.GetString("CharacteristicType_Cylindricity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diameter.
        /// </summary>
        public static string CharacteristicType_Diameter {
            get {
                return ResourceManager.GetString("CharacteristicType_Diameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string CharacteristicType_Distance {
            get {
                return ResourceManager.GetString("CharacteristicType_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flatness.
        /// </summary>
        public static string CharacteristicType_Flatness {
            get {
                return ResourceManager.GetString("CharacteristicType_Flatness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line profile.
        /// </summary>
        public static string CharacteristicType_LineProfile {
            get {
                return ResourceManager.GetString("CharacteristicType_LineProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parallelism.
        /// </summary>
        public static string CharacteristicType_Parallelism {
            get {
                return ResourceManager.GetString("CharacteristicType_Parallelism", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perpendicularity.
        /// </summary>
        public static string CharacteristicType_Perpendicularity {
            get {
                return ResourceManager.GetString("CharacteristicType_Perpendicularity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string CharacteristicType_Position {
            get {
                return ResourceManager.GetString("CharacteristicType_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius.
        /// </summary>
        public static string CharacteristicType_Radius {
            get {
                return ResourceManager.GetString("CharacteristicType_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R coordinate.
        /// </summary>
        public static string CharacteristicType_RCoordinate {
            get {
                return ResourceManager.GetString("CharacteristicType_RCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roundness.
        /// </summary>
        public static string CharacteristicType_Roundness {
            get {
                return ResourceManager.GetString("CharacteristicType_Roundness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slope angle.
        /// </summary>
        public static string CharacteristicType_SlopeAngle {
            get {
                return ResourceManager.GetString("CharacteristicType_SlopeAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphericity.
        /// </summary>
        public static string CharacteristicType_Sphericity {
            get {
                return ResourceManager.GetString("CharacteristicType_Sphericity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straightness.
        /// </summary>
        public static string CharacteristicType_Straightness {
            get {
                return ResourceManager.GetString("CharacteristicType_Straightness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surface profile.
        /// </summary>
        public static string CharacteristicType_SurfaceProfile {
            get {
                return ResourceManager.GetString("CharacteristicType_SurfaceProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symmetry.
        /// </summary>
        public static string CharacteristicType_Symmetry {
            get {
                return ResourceManager.GetString("CharacteristicType_Symmetry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taper angle.
        /// </summary>
        public static string CharacteristicType_TaperAngle {
            get {
                return ResourceManager.GetString("CharacteristicType_TaperAngle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        public static string CharacteristicType_Thickness {
            get {
                return ResourceManager.GetString("CharacteristicType_Thickness", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total runout.
        /// </summary>
        public static string CharacteristicType_TotalRunout {
            get {
                return ResourceManager.GetString("CharacteristicType_TotalRunout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string CharacteristicType_Width {
            get {
                return ResourceManager.GetString("CharacteristicType_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X coordinate.
        /// </summary>
        public static string CharacteristicType_XCoordinate {
            get {
                return ResourceManager.GetString("CharacteristicType_XCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Y coordinate.
        /// </summary>
        public static string CharacteristicType_YCoordinate {
            get {
                return ResourceManager.GetString("CharacteristicType_YCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z coordinate.
        /// </summary>
        public static string CharacteristicType_ZCoordinate {
            get {
                return ResourceManager.GetString("CharacteristicType_ZCoordinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charts.
        /// </summary>
        public static string ChartString {
            get {
                return ResourceManager.GetString("ChartString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Columns:.
        /// </summary>
        public static string ChooseColumnsString {
            get {
                return ResourceManager.GetString("ChooseColumnsString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear filter.
        /// </summary>
        public static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Sorting by &quot;{0}&quot;.
        /// </summary>
        public static string ClearSortingString {
            get {
                return ResourceManager.GetString("ClearSortingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes to data service before closing?.
        /// </summary>
        public static string CloseWorkspaceConfirmationDialogMessage {
            get {
                return ResourceManager.GetString("CloseWorkspaceConfirmationDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save File.
        /// </summary>
        public static string CloseWorkspaceConfirmationDialogTitle {
            get {
                return ResourceManager.GetString("CloseWorkspaceConfirmationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE.
        /// </summary>
        public static string CreateTemplateProceedButtonText {
            get {
                return ResourceManager.GetString("CreateTemplateProceedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not connect to the MiCAT Data Service..
        /// </summary>
        public static string DataServiceConnectionErrorMessage {
            get {
                return ResourceManager.GetString("DataServiceConnectionErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Service Connection Error.
        /// </summary>
        public static string DataServiceConnectionErrorTitle {
            get {
                return ResourceManager.GetString("DataServiceConnectionErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _.
        /// </summary>
        public static string DataSourcePanelTitle {
            get {
                return ResourceManager.GetString("DataSourcePanelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DELETE.
        /// </summary>
        public static string DeleteButtonLabel {
            get {
                return ResourceManager.GetString("DeleteButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This program and its associated runs will be permanently deleted from the data service..
        /// </summary>
        public static string DeletePlanMessage {
            get {
                return ResourceManager.GetString("DeletePlanMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Program.
        /// </summary>
        public static string DeletePlanTitle {
            get {
                return ResourceManager.GetString("DeletePlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This run will be permanently deleted from the data service..
        /// </summary>
        public static string DeleteRunMessage {
            get {
                return ResourceManager.GetString("DeleteRunMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Run.
        /// </summary>
        public static string DeleteRunTitle {
            get {
                return ResourceManager.GetString("DeleteRunTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteTemplateLabel {
            get {
                return ResourceManager.GetString("DeleteTemplateLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template will be removed from the library and permanently deleted from the data service..
        /// </summary>
        public static string DeleteTemplateMessage {
            get {
                return ResourceManager.GetString("DeleteTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Template.
        /// </summary>
        public static string DeleteTemplateTitle {
            get {
                return ResourceManager.GetString("DeleteTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete from MiCAT Data Service..
        /// </summary>
        public static string DeletingDataErrorMessage {
            get {
                return ResourceManager.GetString("DeletingDataErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deviation.
        /// </summary>
        public static string Deviation {
            get {
                return ResourceManager.GetString("Deviation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image files.
        /// </summary>
        public static string DialogImagesExtensions {
            get {
                return ResourceManager.GetString("DialogImagesExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Image.
        /// </summary>
        public static string DialogImagesTitle {
            get {
                return ResourceManager.GetString("DialogImagesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        public static string DoYouWantToContinue {
            get {
                return ResourceManager.GetString("DoYouWantToContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit filter.
        /// </summary>
        public static string EditFilter {
            get {
                return ResourceManager.GetString("EditFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TEMPLATE.
        /// </summary>
        public static string EditReport {
            get {
                return ResourceManager.GetString("EditReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDIT.
        /// </summary>
        public static string EditTemplateProceedButtonText {
            get {
                return ResourceManager.GetString("EditTemplateProceedButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Report to a standard file type..
        /// </summary>
        public static string ExportToolTipString {
            get {
                return ResourceManager.GetString("ExportToolTipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF.
        /// </summary>
        public static string ExportToPDF {
            get {
                return ResourceManager.GetString("ExportToPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string ExportToPDFFileName {
            get {
                return ResourceManager.GetString("ExportToPDFFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string ExportToPDFFileTypeDesc {
            get {
                return ResourceManager.GetString("ExportToPDFFileTypeDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string ExportToPDFTitle {
            get {
                return ResourceManager.GetString("ExportToPDFTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to PDF.
        /// </summary>
        public static string ExportToPDFToolTip {
            get {
                return ResourceManager.GetString("ExportToPDFToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Name.
        /// </summary>
        public static string FeatureName {
            get {
                return ResourceManager.GetString("FeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feature Table.
        /// </summary>
        public static string FeatureTableString {
            get {
                return ResourceManager.GetString("FeatureTableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string FieldItem_Comment {
            get {
                return ResourceManager.GetString("FieldItem_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Company name.
        /// </summary>
        public static string FieldItem_CompanyName {
            get {
                return ResourceManager.GetString("FieldItem_CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DME name.
        /// </summary>
        public static string FieldItem_DMEName {
            get {
                return ResourceManager.GetString("FieldItem_DMEName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing number.
        /// </summary>
        public static string FieldItem_DrawingNumber {
            get {
                return ResourceManager.GetString("FieldItem_DrawingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot number.
        /// </summary>
        public static string FieldItem_LotNumber {
            get {
                return ResourceManager.GetString("FieldItem_LotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine ID.
        /// </summary>
        public static string FieldItem_MachineId {
            get {
                return ResourceManager.GetString("FieldItem_MachineId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model number.
        /// </summary>
        public static string FieldItem_ModelNumber {
            get {
                return ResourceManager.GetString("FieldItem_ModelNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator name.
        /// </summary>
        public static string FieldItem_OperatorName {
            get {
                return ResourceManager.GetString("FieldItem_OperatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part description.
        /// </summary>
        public static string FieldItem_PartDescription {
            get {
                return ResourceManager.GetString("FieldItem_PartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part name.
        /// </summary>
        public static string FieldItem_PartName {
            get {
                return ResourceManager.GetString("FieldItem_PartName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part number.
        /// </summary>
        public static string FieldItem_PartNumber {
            get {
                return ResourceManager.GetString("FieldItem_PartNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan name.
        /// </summary>
        public static string FieldItem_PlanName {
            get {
                return ResourceManager.GetString("FieldItem_PlanName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan version.
        /// </summary>
        public static string FieldItem_PlanVersion {
            get {
                return ResourceManager.GetString("FieldItem_PlanVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select property.
        /// </summary>
        public static string FieldItem_SelectProperty {
            get {
                return ResourceManager.GetString("FieldItem_SelectProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial number.
        /// </summary>
        public static string FieldItem_SerialNumber {
            get {
                return ResourceManager.GetString("FieldItem_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        public static string FieldItem_Temperature {
            get {
                return ResourceManager.GetString("FieldItem_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time stamp.
        /// </summary>
        public static string FieldItem_TimeStamp {
            get {
                return ResourceManager.GetString("FieldItem_TimeStamp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string FieldItem_UserName {
            get {
                return ResourceManager.GetString("FieldItem_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string FilterToolTipString {
            get {
                return ResourceManager.GetString("FilterToolTipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Footer.
        /// </summary>
        public static string FooterToolTipString {
            get {
                return ResourceManager.GetString("FooterToolTipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected error..
        /// </summary>
        public static string GenericError {
            get {
                return ResourceManager.GetString("GenericError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource not found..
        /// </summary>
        public static string GenericNotFoundError {
            get {
                return ResourceManager.GetString("GenericNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string GetDataString {
            get {
                return ResourceManager.GetString("GetDataString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string GetDataToolTipString {
            get {
                return ResourceManager.GetString("GetDataToolTipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by &quot;{0}&quot;.
        /// </summary>
        public static string GroupByString {
            get {
                return ResourceManager.GetString("GroupByString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Form.
        /// </summary>
        public static string HeaderFormString {
            get {
                return ResourceManager.GetString("HeaderFormString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icon.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        public static string ImageString {
            get {
                return ResourceManager.GetString("ImageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert image.
        /// </summary>
        public static string ImageToolTipString {
            get {
                return ResourceManager.GetString("ImageToolTipString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template version is not supported by current application version..
        /// </summary>
        public static string IncompatibleTemplateErrorMessage {
            get {
                return ResourceManager.GetString("IncompatibleTemplateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incompatible Template Version.
        /// </summary>
        public static string IncompatibleTemplateErrorTitle {
            get {
                return ResourceManager.GetString("IncompatibleTemplateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The template cannot be read due to an invalid format or content error..
        /// </summary>
        public static string InvalidTemplateErrorMessage {
            get {
                return ResourceManager.GetString("InvalidTemplateErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Template.
        /// </summary>
        public static string InvalidTemplateErrorTitle {
            get {
                return ResourceManager.GetString("InvalidTemplateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiCAT Template 1.
        /// </summary>
        public static string LocalKey_MiCATTemplate1 {
            get {
                return ResourceManager.GetString("LocalKey_MiCATTemplate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiCAT Template 2.
        /// </summary>
        public static string LocalKey_MiCATTemplate2 {
            get {
                return ResourceManager.GetString("LocalKey_MiCATTemplate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Tol..
        /// </summary>
        public static string LowerTolerance {
            get {
                return ResourceManager.GetString("LowerTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export As.
        /// </summary>
        public static string MainToolbarExportAs {
            get {
                return ResourceManager.GetString("MainToolbarExportAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV.
        /// </summary>
        public static string MainToolbarExportAsCSV {
            get {
                return ResourceManager.GetString("MainToolbarExportAsCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data as a CSV file.
        /// </summary>
        public static string MainToolbarExportAsCSVTooltip {
            get {
                return ResourceManager.GetString("MainToolbarExportAsCSVTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string MainToolbarExportAsPDF {
            get {
                return ResourceManager.GetString("MainToolbarExportAsPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export the report as a PDF file.
        /// </summary>
        public static string MainToolbarExportAsPDFTooltip {
            get {
                return ResourceManager.GetString("MainToolbarExportAsPDFTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export as a file type.
        /// </summary>
        public static string MainToolbarExportAsTooltip {
            get {
                return ResourceManager.GetString("MainToolbarExportAsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top: 1.27 cm  Bottom: 1.27 cm.
        /// </summary>
        public static string MarginDescriptionNarrow {
            get {
                return ResourceManager.GetString("MarginDescriptionNarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top: 2.54 cm  Bottom: 2.54 cm.
        /// </summary>
        public static string MarginDescriptionNormal {
            get {
                return ResourceManager.GetString("MarginDescriptionNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Narrow.
        /// </summary>
        public static string MarginNarrow {
            get {
                return ResourceManager.GetString("MarginNarrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string MarginNormal {
            get {
                return ResourceManager.GetString("MarginNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measured.
        /// </summary>
        public static string Measured {
            get {
                return ResourceManager.GetString("Measured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Table.
        /// </summary>
        public static string MeasurementTableString {
            get {
                return ResourceManager.GetString("MeasurementTableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiCAT Help....
        /// </summary>
        public static string MiCATHelp {
            get {
                return ResourceManager.GetString("MiCATHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO.
        /// </summary>
        public static string NoButtonLabel {
            get {
                return ResourceManager.GetString("NoButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nominal.
        /// </summary>
        public static string Nominal {
            get {
                return ResourceManager.GetString("Nominal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Programs Available.
        /// </summary>
        public static string NoProgramsAvailable {
            get {
                return ResourceManager.GetString("NoProgramsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Runs Available.
        /// </summary>
        public static string NoRunsAvailable {
            get {
                return ResourceManager.GetString("NoRunsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select run to display filter content.
        /// </summary>
        public static string NoRunSelectedForFeatureName {
            get {
                return ResourceManager.GetString("NoRunSelectedForFeatureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string NotEvaluated {
            get {
                return ResourceManager.GetString("NotEvaluated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OkButtonLabel {
            get {
                return ResourceManager.GetString("OkButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file is currently in use. Please save with a different file name or in a different folder..
        /// </summary>
        public static string OpenedFileMessage {
            get {
                return ResourceManager.GetString("OpenedFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as file.
        /// </summary>
        public static string OpenedFileTitle {
            get {
                return ResourceManager.GetString("OpenedFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Margins.
        /// </summary>
        public static string PageMargins {
            get {
                return ResourceManager.GetString("PageMargins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Size.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A4.
        /// </summary>
        public static string PageSizeA4 {
            get {
                return ResourceManager.GetString("PageSizeA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter.
        /// </summary>
        public static string PageSizeLetter {
            get {
                return ResourceManager.GetString("PageSizeLetter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page {0} of {1}.
        /// </summary>
        public static string PageString {
            get {
                return ResourceManager.GetString("PageString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load part because the part cannot be found in the data service..
        /// </summary>
        public static string PartNotFoundMessage {
            get {
                return ResourceManager.GetString("PartNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Part Error.
        /// </summary>
        public static string PartNotFoundTitle {
            get {
                return ResourceManager.GetString("PartNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete program because the program cannot be found..
        /// </summary>
        public static string PlanCouldNotBeDeletedMessage {
            get {
                return ResourceManager.GetString("PlanCouldNotBeDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Program Error.
        /// </summary>
        public static string PlanCouldNotBeDeletedTitle {
            get {
                return ResourceManager.GetString("PlanCouldNotBeDeletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load program because the program cannot be found
        ///in the data service..
        /// </summary>
        public static string PlanNotFoundMessage {
            get {
                return ResourceManager.GetString("PlanNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Program Error.
        /// </summary>
        public static string PlanNotFoundTitle {
            get {
                return ResourceManager.GetString("PlanNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plot.
        /// </summary>
        public static string PlotString {
            get {
                return ResourceManager.GetString("PlotString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Program.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo (Ctrl+Y).
        /// </summary>
        public static string RedoToolTip {
            get {
                return ResourceManager.GetString("RedoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshToolTip {
            get {
                return ResourceManager.GetString("RefreshToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data could not be retrieved from data service..
        /// </summary>
        public static string RetrievingDataErrorMessage {
            get {
                return ResourceManager.GetString("RetrievingDataErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string RetrievingDataErrorTitle {
            get {
                return ResourceManager.GetString("RetrievingDataErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete run because the run cannot be found..
        /// </summary>
        public static string RunCouldNotBeDeletedMessage {
            get {
                return ResourceManager.GetString("RunCouldNotBeDeletedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Run Error.
        /// </summary>
        public static string RunCouldNotBeDeletedTitle {
            get {
                return ResourceManager.GetString("RunCouldNotBeDeletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load run because the run cannot be found in the data service..
        /// </summary>
        public static string RunNotFoundMessage {
            get {
                return ResourceManager.GetString("RunNotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load Run Error.
        /// </summary>
        public static string RunNotFoundTitle {
            get {
                return ResourceManager.GetString("RunNotFoundTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string Runs {
            get {
                return ResourceManager.GetString("Runs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save successful!.
        /// </summary>
        public static string SaveSuccessMessage {
            get {
                return ResourceManager.GetString("SaveSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveSuccessTitle {
            get {
                return ResourceManager.GetString("SaveSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As.
        /// </summary>
        public static string SaveTemplate {
            get {
                return ResourceManager.GetString("SaveTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string SaveTemplateCancelButton {
            get {
                return ResourceManager.GetString("SaveTemplateCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As (Data Service).
        /// </summary>
        public static string SaveTemplateDialogTitle {
            get {
                return ResourceManager.GetString("SaveTemplateDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template name.
        /// </summary>
        public static string SaveTemplateName {
            get {
                return ResourceManager.GetString("SaveTemplateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SAVE.
        /// </summary>
        public static string SaveTemplateNameSaveButton {
            get {
                return ResourceManager.GetString("SaveTemplateNameSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Template.
        /// </summary>
        public static string SaveTemplateTitle {
            get {
                return ResourceManager.GetString("SaveTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveToolTip {
            get {
                return ResourceManager.GetString("SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CANCEL.
        /// </summary>
        public static string SelectTemplateCancelButton {
            get {
                return ResourceManager.GetString("SelectTemplateCancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Template.
        /// </summary>
        public static string SelectTemplateForEditTitle {
            get {
                return ResourceManager.GetString("SelectTemplateForEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates ({0}).
        /// </summary>
        public static string SelectTemplateSubTitle {
            get {
                return ResourceManager.GetString("SelectTemplateSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Report.
        /// </summary>
        public static string SelectTemplateTitle {
            get {
                return ResourceManager.GetString("SelectTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes.
        /// </summary>
        public static string ShapesString {
            get {
                return ResourceManager.GetString("ShapesString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Ascending by &quot;{0}&quot;.
        /// </summary>
        public static string SortAscendingString {
            get {
                return ResourceManager.GetString("SortAscendingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Descending by &quot;{0}&quot;.
        /// </summary>
        public static string SortDescendingString {
            get {
                return ResourceManager.GetString("SortDescendingString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        public static string TableString {
            get {
                return ResourceManager.GetString("TableString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Textbox.
        /// </summary>
        public static string TextboxString {
            get {
                return ResourceManager.GetString("TextboxString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align center.
        /// </summary>
        public static string TextBoxToolbarAlignCenterToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolbarAlignCenterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        public static string TextBoxToolbarBoldToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolbarBoldToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bullets.
        /// </summary>
        public static string TextBoxToolbarBulletsToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolbarBulletsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease font size.
        /// </summary>
        public static string TextBoxToolbarDecreaseFontSizeToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolbarDecreaseFontSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease indent.
        /// </summary>
        public static string TextBoxToolbarDecreaseLeftIndentToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolbarDecreaseLeftIndentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font type.
        /// </summary>
        public static string TextBoxToolbarFontFamilyToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolbarFontFamilyToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string TextBoxToolbarFontSizeToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolbarFontSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font color.
        /// </summary>
        public static string TextBoxToolbarForeColorToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolbarForeColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text highlight color.
        /// </summary>
        public static string TextBoxToolbarHighlightColorToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolbarHighlightColorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase font size.
        /// </summary>
        public static string TextBoxToolbarIncreaseFontSizeToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolbarIncreaseFontSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase indent.
        /// </summary>
        public static string TextBoxToolbarIncreaseLeftIndentToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolbarIncreaseLeftIndentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        public static string TextBoxToolbarItalicToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolbarItalicToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numbering.
        /// </summary>
        public static string TextBoxToolbarNumberedToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolbarNumberedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        public static string TextBoxToolbarUnderlineToolTip {
            get {
                return ResourceManager.GetString("TextBoxToolbarUnderlineToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tolerance Graphic.
        /// </summary>
        public static string ToleranceGraphic {
            get {
                return ResourceManager.GetString("ToleranceGraphic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo (Ctrl+Z).
        /// </summary>
        public static string UndoToolTip {
            get {
                return ResourceManager.GetString("UndoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup by &quot;{0}&quot;.
        /// </summary>
        public static string UngroupByString {
            get {
                return ResourceManager.GetString("UngroupByString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Tol..
        /// </summary>
        public static string UpperTolerance {
            get {
                return ResourceManager.GetString("UpperTolerance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT.
        /// </summary>
        public static string ViewReport {
            get {
                return ResourceManager.GetString("ViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert text here.
        /// </summary>
        public static string WaterMarkTextBoxString {
            get {
                return ResourceManager.GetString("WaterMarkTextBoxString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YES.
        /// </summary>
        public static string YesButtonLabel {
            get {
                return ResourceManager.GetString("YesButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom range from 10% to 400%.
        /// </summary>
        public static string ZoomComboBoxTooltip {
            get {
                return ResourceManager.GetString("ZoomComboBoxTooltip", resourceCulture);
            }
        }
    }
}
